services:
  dev-db2:
    image: mysql:8
    container_name: dev-db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db2
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - '3307:3306'
    volumes:
      - ./db2:/var/lib/mysql
    networks:
      - dev-network

networks:
  dev-network:
