GET  http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZjhkNWFiMS1iOGM1LTQ2NTktOWZhZS0wNmZhOGVlZWZmOTYiLCJlbWFpbCI6Im1paGFpNEB5YWhvby5jb20iLCJyb2xlcyI6W10sInBlcm1pc3Npb25zIjpbXSwiaWF0IjoxNzI4OTkzODE3LCJleHAiOjE3Mjg5OTQ3MTd9.99AOB9WJa4jiCLHSu8Tr339YCmxk0djCf0Teck4QjHc