POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "mihai4@yahoo.com",
    "password": "mihailol"
}



#############################################


POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "mihai4@yahoo.com",
    "password": "mihailol"
}
